repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.11.0
    hooks:
    -   id: black
        entry: bash -c "cd conquest2a && black ."
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'c2738302f5cf2bfb559c1f210950badb133613ea'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [numpy>=2.0.0]
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: ^tests/examples/
